name: Job Crawler Automation

on:
  schedule:
    - cron: '2 3 * * *' # UTC 00:00 = KST 09:00
  workflow_dispatch:   # 버튼 눌러서 수동 실행 가능하도록 설정

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # CSV 파일을 저장(Push)하기 위해 필요
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

# ... (앞부분 동일)
      - name: Run Crawler
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add jobs_*.csv  # 모든 날짜별 CSV 파일을 저장소에 기록
          git commit -m "Update job list $(date +'%Y-%m-%d')" || exit 0
          git push
